spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=healthcare_service_schema
    username: postgres
    password: 3833415
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: healthcare_service_schema
        format_spl: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: healthcare_service_schema
server:
  port: 8080
jwt:
  secret-key: thisissecretkeyoftrido@additionalwordtoget256bitsenough
  access-token-validity: 900
  refresh-token-validity: 86400

