spring:
  datasource:
    #    url: jdbc:postgresql://ec2-54-85-113-73.compute-1.amazonaws.com:5432/dd26is8qghtdp7?sslmode=require&currentSchema=healthcare_service_schema
    #    username:
    #    password:
    #    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=healthcare_service_schema
    #    username: postgres
    #    password: 3833415
    url: ${DATASOURCE_URL}?currentSchema=healthcare_service_schema
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: healthcare_service_schema
        format_spl: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: healthcare_service_schema
  servlet:
    multipart:
      max-file-size: 10MB
server:
  error:
    include-message: always
  port: ${PORT:8080}
jwt:
  secret-key: thisissecretkeyoftrido@additionalwordtoget256bitsenough
  access-token-validity: 3600
  refresh-token-validity: 86400
api:
  prefix: /api

